@startuml
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
int main()
{
if(1==1)
if(1==1)
if (S1){
/* Operation Generate Attendance Report */
/* Operation Add Faculty new to database */
/* Operation Add New Student to database */
}
else

while (I1)
/* Try again to login */
if (S2)
if(1==1)
if (S3)
if (S4)
/* Operation mark attendance */
else
/* Operation Show Attendance reaport */
else
while (I2)
/* Try again to login */
else {
/* name */
/* email */
/* contact no. */
/* password */
/* Operation submit registration form */
} if (
S5)
if(1==1)
if (S6)
if(1==1)
/* Operation Show Attendance reaport */
else
while (I3)
/* Try again to login */
else {
/* name */
/* email */
/* contact no. */
/* password */
/* Operation submit registration form */
}
}
@enduml